### PR TITLE
Upgrade PyCTM to python3

### PR DESCRIPTION
**Pull request by adbedada**
Upgrade PyCTM based on the work of @fdtomasi

### CODE REVIEW

**Comment by kzhai** [comment]
@fdtomasi @adbeda Thanks for the updates.

**Comment by kzhai** [comment]
@fdtomasi I also updated the README with a minor bug fix. Please re-sync the master later.

**Comment by adbedada** [comment]
@kzhai thanks for merging @fdtomasi update. If you create a [release](https://github.com/kzhai/PyCTM/releases) for PyCTM, I can go ahead and start building the recipe to pull it to conda-forge.

Best,

**Comment by kzhai** [comment]
@adbeda Thanks, just created a v0.1 release.

**Pull request merged**
